### ISSUE TITLE
Program is deleted shortly after opening

### ISSUE THREAD

**Issue by MoeGuitarist** [delthas/autopunch#10]
Whenever I launch, the window is closed and the program deleted a few seconds after. When running in admin mode it will occasionally keep open, but the issue will repeat on next launch.

**Comment by delthas** [comment]
Likely an antivirus issue. Check your AV quarantines

**Comment by MoeGuitarist** [comment]
oh of course, why didn't I think of checking that. issue resolved, thanks for the help!
