### ISSUE TITLE
Porting to Python

### ISSUE THREAD

**Issue by brostosjoined** [delthas/autopunch#12]
I want to implement this in pure python code in cli could you like please give a simple description of what the code does like sends a request to https://delthas.fr/ then it gets a response ..... @delthas

**Comment by delthas** [comment]
Any reason why you want to reimplement it in Python? Is it just to have an automated script?

**Comment by brostosjoined** [comment]
I already ported proxy punch so am leaving this out  if you have the latest version you could send me that.
